var poeSkills = [
  "Animate Guardian",
  "Cleave",
  "Dominating Blow",
  "Flame Totem",
  "Glacial Hammer",
  "Ground Slam",
  "Heavy Strike",
  "Infernal Blow",
  "Leap Slam",
  "Lightning Strike",
  "Molten Strike",
  "Searing Bond",
  "Shield Charge",
  "Shockwave Totem",
  "Static Strike",
  "Sweep",
  "Animate Weapon",
  "Barrage",
  "Bear Trap",
  "Burning Arrow",
  "Cyclone",
  "Desecrate",
  "Detonate Dead",
  "Double Strike",
  "Dual Strike",
  "Elemental Hit",
  "Etheral Knives",
  "Explosive Arrow",
  "Fire Trap",
  "Flicker Strike",
  "Freeze Mine",
  "Frenzy",
  "Ice Shot",
  "Lightning Arrow",
  "Poison Arrow",
  "Puncture",
  "Rain of Arrows",
  "Reave",
  "Spectral Throw",
  "Split Arrow",
  "Tornado Shot",
  "Viper Strike",
  "Whirling Blades",
  "Arc",
  "Ball Lightning",
  "Cold Snap",
  "Conversion Trap",
  "Discharge",
  "Fireball",
  "Firestorm",
  "Flame Surge",
  "Flameblast",
  "Freezing Pulse",
  "Frost Wall",
  "Glacial Cascade",
  "Ice Nova",
  "Ice Spear",
  "Incinerate",
  "Kinetic Blast",
  "Lightning Tendrils",
  "Lightning Warp",
  "Power Siphon",
  "Raise Spectre",
  "Raise Zombie",
  "Righteous Fire",
  "Shock Nova",
  "Spark",
  "Storm Call",
  "Summon Ragin Spirit",
  "Summon Skeletons",
  "Magma Orb",
  "Wild Strike",
  "Frost Blade",
  "Flame Dash",
  "Ice Crash",
  "Lightning Warp",
  "Fire Nova Mine",
  "Flame Dash"
];